eureka:
  instance:
    hostname: ${DOMAIN_NAME}
  client:
    serviceUrl:
      defaultZone: https://eureka-kpociot.herokuapp.com/eureka/

spring:
  application:
    name: hcb-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: hcb-accounts
        uri: lb://hcb-accounts
        predicates:
        - Path=/accounts/**
        filters:
        - RewritePath=/accounts/(?<path>), /$\{path}
      - id: frontend
        uri: https://accounting-kpociot.herokuapp.com
        predicates:
        - Path=/**
        filters:
        - RewritePath=/(?<path>), /$\{path}